services:
  - type: web
    name: movie-booking-backend
    env: node
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        fromDatabase: movie-booking-db
        keyFrom: connectionString
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: EMAIL_USER
        value: your_email@gmail.com
      - key: EMAIL_PASS
        value: your_email_password
